### ISSUE TITLE
export_png failing for group_by plots

### ISSUE THREAD

**Issue by barryrowlingson** [rstudio/ggvis#332]
This works

```
  > p=mtcars %>% 
     ggvis(~wt, ~mpg) %>% 
     layer_points(fill = ~factor(cyl))
  > export_png(p,"plot1.png")
  > 
```

But this fails

```
 > p=mtcars %>% 
    ggvis(~wt, ~mpg, fill = ~factor(cyl)) %>% 
    layer_points() %>% 
    group_by(cyl) %>% 
    layer_model_predictions(model = "lm")
> export_png(p,"plot1.png")
 /usr/local/lib/node_modules/vega/vega.js:4799
   var tx = vg.data[def.type]();
                             ^
 TypeError: Property 'treefacet' of object #<Object> is not a function
     at vg.parse.transform (/usr/local/lib/node_modules/vega/vega.js:4799:29)
     at Array.map (native)
     at Object.vg.parse.dataflow (/usr/local/lib/node_modules/vega/vega.js:4261:34)
     at /usr/local/lib/node_modules/vega/vega.js:4234:27
     at Array.forEach (native)
     at Object.vg.parse.data (/usr/local/lib/node_modules/vega/vega.js:4223:16)
     at parse (/usr/local/lib/node_modules/vega/vega.js:4788:22)
     at Object.vg.parse.spec (/usr/local/lib/node_modules/vega/vega.js:4794:23)
     at Object.vg.headless.render (/usr/local/lib/node_modules/vega/vega.js:7248:12)
     at render (/usr/local/lib/node_modules/vega/bin/vg2png:55:15)
```

R 3.1.1, ggvis 0.4, and the following node modules:

```
    vega@1.4.2 /usr/local/lib/node_modules/vega
    ├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
    ├── d3-geo-projection@0.2.10
    ├── topojson@1.6.14 (queue-async@1.0.7, rw@0.0.10, optimist@0.3.7, shapefile@0.3.0)
    ├── d3@3.4.10 (jsdom@0.5.7)
    └── canvas@1.1.3 (nan@0.4.4)
```

A similar error has been reported on the ggvis google group but I thought it should go here.

**Comment by lucasxteixeira** [comment]
I have also commented this on the ggvis google group.
I'm facing the exact same issue when trying to export a simple boxplot.
Moreover, any grouping does not work.

**Comment by skanskan** [comment]
Where can I get vg2png or Vega for Windows?
